- name: Install PostgreSQL
  apt:
    name:
      - "{{ package_map[ansible_distribution_release] }}"
      - "python3-psycopg2"
      - "acl"
    update_cache: true
    cache_valid_time: 3600
    state: present
  vars:
    package_map:
      focal: postgresql-14
      jammy: postgresql-14
      noble: postgresql-16
  register: _result_apt

- name: Create MAAS Postgres User
  community.postgresql.postgresql_user:
    name: "{{ maas_postgres_user }}"
    password: "{{ maas_postgres_password }}"
    login_user: "postgres"
    state: present
  become: true
  become_user: postgres

- name: Create MAAS Postgres Database
  community.postgresql.postgresql_db:
    name: "{{ maas_postgres_database }}"
    state: present
    owner: "{{ maas_postgres_user }}"
  become: true
  become_user: postgres
