- name: Change password from vars
  user:
    name: "{{ item.name }}"
    password: >-
      {{
        item.pass.startswith('$6$')
          | ternary(item.pass, item.pass | password_hash('sha512'))
      }}
  loop: "{{ users }}"
  when: item.pass is defined

- name: Change password from input
  user:
    name: "{{ item.name }}"
    password: "{{ input_pass_hash }}"
  loop: "{{ users }}"
  when: item.pass is not defined
